version: "3"
services:
  db:
    image: postgres
    container_name: my-app-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis-session-storage
    restart: always
    ports:
      - "6379:6379"
  web-server:
    container_name: my-app-web-server
    build: ./server/
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - "db"
    links: 
      - "db"
volumes:
  my-db:
